import { CancelToken } from 'axios';
import * as React from 'react';
import { EntityValues } from '../services/entity/EntityService';
import { ChildDecoratorProps, ChildDecoratorType, DynamicAutocompleteGetterTypeArgs, EntityAclType, FetchFksCallback, OrderDirection, calculateAclType } from './EntityInterface';
import autoForeignKeyResolver from './DefaultEntityBehavior/AutoForeignKeyResolver';
import autoSelectOptions, { autoSelectOptionHandlers } from './DefaultEntityBehavior/AutoSelectOptions';
import filterFieldsetGroups, { FieldsetGroups } from './DefaultEntityBehavior/FilterFieldsetGroups';
import foreignKeyGetter from './DefaultEntityBehavior/ForeignKeyGetter';
import foreignKeyResolver from './DefaultEntityBehavior/ForeignKeyResolver';
import { EntityFormProps, EntityFormType, FkChoices, Form, NullablePropertyFkChoices, PropertyFkChoices } from './DefaultEntityBehavior/Form/index';
import ListDecorator from './DefaultEntityBehavior/ListDecorator';
import marshaller, { MarshallerValues } from './DefaultEntityBehavior/Marshaller';
import unmarshaller from './DefaultEntityBehavior/Unmarshaller';
import validator from './DefaultEntityBehavior/Validator';
import View from './DefaultEntityBehavior/View';
export declare const initialValues: {};
export declare const columns: never[];
export declare const properties: {};
export declare const acl: EntityAclType;
export declare const calculateAclByParentRow: calculateAclType;
export declare const ChildDecorator: ChildDecoratorType;
export declare const ChildDecoratorMemo: React.NamedExoticComponent<React.PropsWithChildren<ChildDecoratorProps>>;
export declare type FormOnChangeEvent = React.ChangeEvent<{
    name: string;
    value: any;
}>;
/** deprecated, use fetchAllPages instead */
declare const fetchFks: (endpoint: string, properties: Array<EntityValues> | Array<string>, setter: FetchFksCallback, cancelToken?: CancelToken) => Promise<unknown>;
export declare type fetchFksType = typeof fetchFks;
declare const DefaultEntityBehavior: {
    initialValues: {};
    validator: import("./EntityInterface").EntityValidator;
    marshaller: (values: MarshallerValues, properties: import("..").PartialPropertyList, whitelist?: string[]) => MarshallerValues;
    unmarshaller: (row: MarshallerValues, properties: import("..").PartialPropertyList) => MarshallerValues;
    foreignKeyResolver: () => Promise<import("./EntityInterface").foreignKeyResolverType>;
    foreignKeyGetter: () => Promise<import("./EntityInterface").ForeignKeyGetterType>;
    dynamicAutocompleteGetters: (props: DynamicAutocompleteGetterTypeArgs) => Promise<Record<string, import("./EntityInterface").SelectOptionsType<any>>>;
    columns: never[];
    properties: {};
    acl: EntityAclType;
    calculateAclByParentRow: calculateAclType;
    List: (props: import("../components/List/Content/ListContent").ListContentProps) => JSX.Element | null;
    ListDecorator: import("./EntityInterface").ListDecoratorType;
    ChildDecorator: React.NamedExoticComponent<React.PropsWithChildren<ChildDecoratorProps>>;
    customActions: {};
    toStr: (row: EntityValues) => string;
    Form: () => Promise<EntityFormType>;
    View: () => Promise<(props: import("./EntityInterface").ViewProps) => JSX.Element | null>;
    fetchFks: (endpoint: string, properties: Array<EntityValues> | Array<string>, setter: FetchFksCallback, cancelToken?: CancelToken) => Promise<unknown>;
    fetchAllFks: (props: import("../helpers/fetchAllPages").fetchAllPagesProps) => Promise<unknown>;
    defaultOrderBy: string;
    defaultOrderDirection: OrderDirection;
};
export default DefaultEntityBehavior;
export { Form, ListDecorator, View, autoForeignKeyResolver, autoSelectOptions, autoSelectOptionHandlers, filterFieldsetGroups, foreignKeyGetter, foreignKeyResolver, marshaller, unmarshaller, validator, };
export type { EntityFormProps, EntityFormType, FieldsetGroups, FkChoices, MarshallerValues, NullablePropertyFkChoices, PropertyFkChoices, };
